{{- with .Values.clusterRole -}}
# ------------------------------
# -- {{ include "app.name" $ | title }} ClusterRoleBinding
# -- Name: {{ include "app.fullname" $ }}-bind
# ------------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" $ }}-bind
  labels:
    {{- include "app.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app.fullname" $ }}-{{ .name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end -}}