{{- $appFullname := (include "app.fullname" .) -}}
{{- $appName := (include "app.name" .) -}}
{{- $appLabels := (include "app.labels" .) -}}
{{- $appSelectorLabels := (include "app.selectorLabels" .) -}}
{{- $enabledServices := (include "app.lib.getServices" .) | fromYaml -}}
{{- range $type, $values := $enabledServices }}
---
# ------------------------------
# -- {{ $appName | title }} Service
# -- Name: {{ $values.serviceName }}
# ------------------------------
apiVersion: v1
kind: Service
metadata:
  name: {{ $values.serviceName }}
  labels:
    {{- $appLabels | nindent 4 }}
spec:
  type: {{ $type }}
  {{- if (eq $type "LoadBalancer") }}
  externalTrafficPolicy: Local
  loadBalancerIP: {{ $values.loadBalancerIP }}
  {{- end }}
  ports:
    {{- range $service, $serviceOptions := $values.services }}
    - name: {{ $service }}
      port: {{ $serviceOptions.port }}
      targetPort: {{ $serviceOptions.port }}
      protocol: {{ $serviceOptions.protocol }}
    {{- end }}
  selector:
    {{- $appSelectorLabels | nindent 4 }}
{{- end }}

