{{- range $containerKey, $containerValues := .Values.containers -}}
{{- if $containerValues.secret }}
---
# ------------------------------
# -- {{ include "app.name" $ | title }} Secret
# -- Name: {{ include "app.fullname" $ }}-{{ $containerKey }}-secret
# ------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" $ }}-{{ $containerKey }}-secret
  labels:
    {{- include "app.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $containerValues.secret }}
  {{ .name }}: {{ .value | trim | b64enc | quote }}
  {{- end }}
{{ end -}}
{{- end -}}