{{- if .Values.ingress.enabled -}}
{{- $appFullname := (include "app.fullname" .) -}}
{{- $kind := .Values.ingress.kind -}}
{{- $subdomainOverride := .Values.ingress.subdomainOverride -}}
{{- $middlewares := .Values.ingress.middlewares -}}
{{- $containers := .Values.containers -}}
{{- $totalDomains := len .Values.ingress.domains -}}
{{- $matchRule := "" -}}
{{- if (eq $kind "IngressRouteTCP") -}}
  {{- $matchRule = "HostSNI" -}}
{{- else -}}
  {{- $matchRule = "Host" -}}
{{- end -}}
{{- $pos := 0 -}}
{{- $ingressName := "" -}}
{{- range $domain := .Values.ingress.domains -}}
{{- $pos = (add 1 $pos) -}}
{{- if (eq $totalDomains 1) -}}
  {{- $ingressName = (cat $appFullname "-rtr" | nospace) -}}
{{- else -}}
  {{- $ingressName = (cat $appFullname "-rtr-" $pos | nospace) -}}
{{- end -}}
{{- $hostname := (cat (coalesce $subdomainOverride $appFullname) "." $domain | nospace) -}}
---
# ------------------------------
# -- {{ include "app.name" $ | title }} {{ $kind }}
# -- Name: {{ $ingressName }}
# ------------------------------
apiVersion: traefik.io/v1alpha1
kind: {{ $kind }}
metadata:
  name: {{ $ingressName }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik-external
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $.Values.ingress.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    {{- range $containerKey, $container := $containers }}
    {{- range $serviceKey, $service := $container.service }}
    {{- if and ($service.enabled) ($service.ingress.enabled) }}
    {{- if ($service.ingress.pathPrefix) }}
    - match: {{ printf "%s(`%s`) && PathPrefix(`%s`)" $matchRule $hostname $service.ingress.pathPrefix }}
    {{- else }}
    - match: {{ printf "%s(`%s`)" $matchRule $hostname }}
    {{- end }}
      {{- if (eq $kind "IngressRoute") }}
      kind: Rule
      {{- end }}
      services:
        - name: {{ $appFullname }}-svc
          port: {{ $service.port }}
      {{- with $middlewares }}
      middlewares:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- if $.Values.ingress.tlsSecret }}
  tls:
    secretName: {{ $.Values.ingress.tlsSecret }}
  {{- else }}
  tls:
    secretName: {{ $domain | replace "." "-" }}-tls
  {{- end }}
{{ end }}
{{ end }}
